apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstackmachinetemplate.gpu.name" . }}
spec:
  template:
    spec:
      flavor: {{ .Values.gpu.flavor }}
      identityRef:
        name: {{ .Values.identityRef.name }}
        region: {{ .Values.identityRef.region }}
        cloudName: {{ .Values.identityRef.cloudName}}
      image:
        filter:
          name: {{ .Values.gpu.image.filter.name }}
          {{- if .Values.gpu.image.filter.tags }}
          tags:
            {{- range $tag := .Values.gpu.image.filter.tags }}
            - {{ $tag }}
            {{- end }}
          {{- end }}
      {{- if gt (len .Values.gpu.portOpts) 0 }}
      portOpts:
        {{ .Values.gpu.portOpts | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.gpu.rootVolume }}
      rootVolume:
        {{ .Values.gpu.rootVolume | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.gpu.additionalBlockDevices) 0 }}
      additionalBlockDevices:
        {{ .Values.gpu.additionalBlockDevices | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.gpu.securityGroups) 0 }}
      securityGroups:
        {{ .Values.gpu.securityGroups | toYaml | nindent 8 }}
      {{- end }}
      {{- if not ( .Values.gpu.sshPublicKey | empty) }}
      sshKeyName: {{ .Values.gpu.sshPublicKey }}
      {{- end }}
