apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    hmc.mirantis.com/managed: "true"
  name: pbasov-templates
  namespace: hmc-system
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/pbasov/k0rdent-templates